'use strict';
const KEY='winter-edit-v1';
const photos={Barcelona:'photo-1539037116277-4db20889f2d4',Naples:'photo-1516483638261-f4dbaf036963',Rome:'photo-1552832230-c0197dd311b5',Milan:'photo-1513581166391-887a96ddeafd',Switzerland:'photo-1464822759023-fed622ff2c3b'};
const photo=(city,w=1000)=>`https://images.unsplash.com/${photos[city]||photos.Switzerland}?auto=format&fit=crop&w=${w}&q=80`;
const day=(date,city,title,subtitle,description,morning,afternoon,evening,transport,note)=>({id:date,date,city,title,subtitle,description,morning,afternoon,evening,transport,note});
const defaults={version:1,people:5,limit:300000,buffer:15,costs:{'Barcelona onward flight & extra-day costs':16000,'Food & coffee':36000,'Intercity trains':24000,'Local transport & coast day':16000,'Ski lessons, passes & rental':32000,'Museums & experiences':15000,'Nightlife & New Year’s':18000,'Insurance, SIM & incidentals':7000},checks:[false,false,false,false,false,false],days:[
day('2026-12-25','Travel','The boys are boarding.','21:00 · depart Hyderabad (HYD)','Depart Hyderabad on 25 December at 21:00 local time. Barcelona arrival is 26 December at 08:00 local time; intermediate connections and airline are not supplied.','Last checks|Check airline baggage rules, passports, tickets and any connection details.','Pack & head to HYD|Follow the airline’s airport arrival guidance; plan to be at the airport at least three hours before departure.','21:00 · take-off|Depart Hyderabad. The overnight journey and time-zone change lead into the Barcelona arrival day.','HYD → BCN · connection details pending','Times supplied by the crew and interpreted as local airport times. Long-haul ticket costs are excluded from the trip budget.'),
day('2026-12-26','Naples','Barcelona in. Naples tonight.','08:00 BCN arrival · onward to Naples','Land in Barcelona at 08:00 local time, complete Schengen entry control if arriving from outside Schengen, then fly onward to Naples the same day. Sleep in Naples tonight.','08:00 · Barcelona arrival|Complete entry passport control in Barcelona if this is your first Schengen arrival. Follow the airport connection procedure for your booking.','Barcelona → Naples|Take your onward flight and transfer to the Naples accommodation. Flight details can be added later.','Pizza & a proper bed|Check in, have a relaxed dinner and rest after the overnight journey from Hyderabad.','HYD → Barcelona → Naples · same-day onward flight','Confirmed crew plan: Barcelona arrival 26 December at 08:00, onward to Naples on 26 December. No Barcelona hotel night.'),
day('2026-12-27','Naples','Ciao, Napoli.','Your first full Naples day','Wake up in Naples with a full day to explore. Espresso, street food and the historic centre set the pace.','A slow Neapolitan morning|Breakfast and espresso, then explore the historic centre.','Get happily lost|Walk Spaccanapoli and stop for sfogliatella. Add the waterfront if the weather is good.','Pizza night, round two|Choose a pizzeria, then drinks around Piazza Bellini.','Naples on foot / local transport','Keep the day relaxed after the journey. Amalfi remains on 28 December and Pompeii on 29 December.'),
day('2026-12-28','Naples','A coast with no crowds.','Amalfi coast · weather-flex day','Trade the summer beach-club fantasy for sea views, quiet lanes and a long lunch. Stay in Naples again tonight.','An early start|Travel to Salerno by train, then use the current coastal bus service toward Amalfi; alternatively compare a five-person driver quote.','Amalfi & a long lunch|Explore Amalfi; add Ravello only if transport, daylight and weather allow.','Back to the city|Return before late connections become sparse. Keep dinner near the accommodation.','Naples ↔ Salerno ↔ Amalfi','Do not rely on winter ferries. Wet-weather swap: Naples Archaeological Museum, cafés and a food walk. Driver allowance is an estimate; confirm luggage/passenger capacity.'),
day('2026-12-29','Naples','Walk through another century.','Pompeii · our pick for your open day','An easy third Naples night beats another hotel change. Pompeii adds something completely different before the city-hopping starts.','Pompeii, unhurried|Take the local train and visit the archaeological park; allow roughly 3 hours on site.','One last Neapolitan lunch|Return to Naples and explore the Spanish Quarter or the waterfront.','Pack, pasta, repeat|Relaxed dinner and bags ready for tomorrow’s train.','Naples ↔ Pompeii','Check winter hours and last admission with the park. Rain alternative: museum day. Skip Vesuvius if visibility or trail conditions are poor.'),
day('2026-12-30','Rome','All roads lead here.','Naples → Rome · ancient city','Take a morning fast train and leave bags at your Rome base. Start the capital with one major sight instead of trying to see everything.','Train & check-in|Naples Centrale → Roma Termini, approximately 1h10–1h20 on a fast train; confirm the published service.','The ancient city|Book a timed Colosseum / Forum visit. Leave time to walk between sites.','Monti after dark|Dinner and wine bars in Monti, followed by a city stroll.','Naples → Rome · fast train','Book the official timed ticket. Short winter daylight makes an early afternoon entry preferable.'),
day('2026-12-31','Rome','Midnight, Roman style.','New Year’s Eve · the big night','The headline night. Keep the daytime gentle enough to have energy for a long dinner and the countdown.','Choose your culture|Optional Vatican Museums slot if open and available; otherwise a slow historic-centre walk.','Espresso & a reset|Pantheon neighbourhood, a late lunch and downtime at the hotel.','Dinner + a paid club night|Plan dinner at 20:00–21:00, then a ticketed party admitting all five before midnight. Room26 is the preferred shortlist; confirm the actual 31 December 2026 package before paying.','Rome base → dinner → Room26, EUR → booked ride home','Paid indoor event only. Allow INR 15,000–20,000 per person for dinner, entry, drinks and shared transport; target INR 18,000 inside the existing nightlife budget, not an additional charge. Confirm five-person admission, entry deadline, dress code and table minimum. NYE event not booked.'),
day('2027-01-01','Rome','A very slow first chapter.','Happy 2027 · recovery mode','A soft landing into the new year: coffee, river walks, excellent pasta. No ambitious museum schedule.','Start late|Brunch and espresso; verify that your chosen café is open.','Rome on foot|Trevi, Spanish Steps and a Tiber walk, adjusted for crowds and weather.','Trastevere table|Book a relaxed dinner and pack for Milan.','Mostly on foot','The Vatican Museums list January 1 as closed. Expect other holiday closures and changed transport schedules.'),
day('2027-01-02','Milan','Switch to city mode.','Rome → Milan · aperitivo hour','Move north by fast train, settle near good transport, and enjoy an evening that feels distinctly Milanese.','Northbound|Rome → Milano Centrale, roughly 3–3.5 hours on a fast service; verify timetable.','Duomo & design|Walk the Duomo square and Galleria. Book rooftop access separately if wanted and operating.','Aperitivo, obviously|Navigli drinks and dinner. Keep the next morning’s Venice train in mind.','Rome → Milan · fast train','Avoid assuming all holiday retail hours are normal. Book railway seats together early.'),
day('2027-01-03','Milan','Take the scenic detour.','Venice day trip · back to Milan','A long but memorable day. Travel light, head beyond the busiest lanes, and reserve the journey home.','Early train to Venice|Milano Centrale → Venezia Santa Lucia. Budget 2.5–3 hours each way, pending timetable.','Canals over checklists|Rialto, quiet Cannaregio lanes and cicchetti. Add San Marco if time allows.','One last canal view|Early dinner, then your booked train back to the same Milan base.','Milan ↔ Venice · return train','Check official access-fee rules for January 2027, plus weather and high-water guidance. Swap for Milan if the long travel day feels too much.'),
day('2027-01-04','Milan','One more, for the city.','Milan · choose your own pace','A day with room to improvise before the Alps. Shop, eat, explore, and get winter kit sorted.','Brera morning|Breakfast, independent shops and neighbourhood wandering.','Pick your Milan|Design museum, Duomo terraces or a long food crawl. Edit this day to your group’s choice.','A good last Italian dinner|Early-ish dinner, laundry and layers packed for Switzerland.','Milan local transport','Check museum Monday closures. Ski clothing is separate from equipment rental; sort waterproof layers before the mountains.'),
day('2027-01-05','Switzerland','From espresso to alpine air.','Milan → Engelberg · settle into the snow','Use today for the transfer and rental fitting, so both following days stay free for skiing.','Cross the border|Plan Milan → Lucerne → Engelberg with SBB; allow roughly 5–6 hours including connections, subject to timetable.','Meet your mountain base|Check in and collect rental gear if the shop allows an evening pickup.','Fondue & an early night|Confirm the lesson meeting point, lift opening and the next morning’s weather.','Milan → Lucerne → Engelberg','Compare tickets before purchasing a Swiss pass. Confirm all changes and leave a connection buffer.'),
day('2027-01-06','Switzerland','First tracks. Big grins.','Ski day 01 · learn the good way','Let a qualified instructor choose the right beginner area for your level and today’s conditions.','Lesson before bravado|Get fitted properly and take a beginner group or shared private lesson.','Practice & hot chocolate|Repeat easy terrain with breaks. Progress only when the instructor says you are ready.','Après, earned|Warm up, swap stories, and have a low-key village dinner.','Village bus / walk to lesson meeting point','Confirm package inclusions: lift pass, skis, boots, helmet and instruction may be sold separately. Stay on suitable open marked pistes.'),
day('2027-01-07','Switzerland','Do it all again. Better.','Ski day 02 · your mountain chapter','A second full day lets you improve instead of just posing with skis. Keep this interchangeable with the first ski day for weather.','Build on yesterday|A second lesson or instructor-approved practice on familiar terrain.','Find your rhythm|Lunch break, more easy runs, then return equipment before the shop closes.','The final crew dinner|Celebrate the trip and pack for the flight day.','Engelberg ski area','If lifts close: Lucerne old town or a village day. Mountain sightseeing is optional, weather-dependent and may need a separate ticket.'),
day('2027-01-08','Switzerland','One last look. Then home.','Engelberg → Zurich · night flight','Leave the mountains in the morning. Zurich is a bonus, not a reason to gamble with the flight.','Down from the mountains|Travel via Lucerne toward Zurich; confirm SBB journey and disruptions the day before.','Zurich, if time allows|Store bags at an appropriate station facility and take a short old-town walk.','Airport, comfortably early|Reach Zurich Airport at least 3 hours before your international departure, or earlier if your airline advises.','Engelberg → Lucerne → Zurich Airport','Exact Zurich departure time is still needed. No skiing today. There is no January 8 hotel night in this plan.'),
day('2027-01-09','Travel','Back in Mumbai.','Arrive BOM · time pending','Arrive in Mumbai on 9 January following the night departure from Zurich on 8 January. Arrival time and any connections are not yet supplied.','Return journey|Follow the airline’s itinerary; route and connection details are still pending.','Mumbai arrival|Complete arrival formalities and collect baggage when your flight arrives.','Homeward|Keep onward plans flexible until the BOM arrival time is confirmed.','ZRH → BOM · flight details pending','Morning/afternoon/evening are planning placeholders, not a confirmed flight schedule. No January 9 accommodation or domestic onward journey is included.')],
stays:[
{city:'Naples',name:'Ostello Bello Naples',start:'2026-12-26',end:'2026-12-30',rate:24000,url:'https://ostellobello.com/en/hostel/naples/',note:'Central social base near Via Toledo. Ask for a private room for five or a suitable room combination; occupancy is unconfirmed.'},
{city:'Rome',name:'YellowSquare Rome',start:'2026-12-30',end:'2027-01-02',rate:35000,url:'https://yellowsquare.com/rome/rooms/',note:'Official site lists private rooms for five. A social base near Termini. Book the New Year’s block first; availability is unconfirmed.'},
{city:'Milan',name:'Ostello Bello Milano Centrale',start:'2027-01-02',end:'2027-01-05',rate:25000,url:'https://www.booking.com/hotel/it/ostello-bello-grande.en-gb.html',note:'Convenient station-area base for the Venice return trip and Swiss departure. Confirm a private 5/6-bed option or two suitable rooms.'},
{city:'Switzerland',name:'H+ Hotel & Spa Engelberg',start:'2027-01-05',end:'2027-01-08',rate:45000,url:'https://www.engelberg.ch/en/seminar-hotels/h-hotel-spa-engelberg/',note:'Village-centre hotel with a wellness area. Compare two rooms for 2 + 3 adults against an apartment. Room configuration is unconfirmed.'}],
};
const checkLabels=['Reserve Rome for New Year’s (30 Dec–2 Jan)','Confirm all stays have beds for all five','Book intercity trains and Venice return seats','Book ski lessons, rental and appropriate lift access','Reserve New Year’s dinner / event','Add flight time; recheck weather & airport transfer'];
const sources=[['Naples accommodation','https://ostellobello.com/en/hostel/naples/'],['Rome room sizes','https://yellowsquare.com/rome/rooms/'],['Milan accommodation','https://www.booking.com/hotel/it/ostello-bello-grande.en-gb.html'],['Engelberg accommodation','https://www.engelberg.ch/en/seminar-hotels/h-hotel-spa-engelberg/'],['Ski school · winter 2026/27','https://www.skischule-engelberg.ch/'],['Ski area & opening dates','https://www.titlis.ch/en/activities/skiing'],['Beginner ski areas','https://www.engelberg.ch/en/winter/ski-snowboard/'],['Rental equipment','https://www.intersportrent.at/skimiete-engelberg/intersport-titlis-rent_3950976'],['Italian rail journeys','https://www.trenitalia.com/en.html'],['Pompeii opening times','https://pompeiisites.org/en/visiting-info/timetables-and-tickets/']];
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₹'+Math.round(n).toLocaleString('en-IN');
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;
const fmt=(s,opts={day:'numeric',month:'short'})=>new Date(s+'T12:00:00Z').toLocaleDateString('en-GB',{...opts,timeZone:'UTC'});
const nights=s=>Math.round((Date.parse(s.end)-Date.parse(s.start))/86400000);
const clone=o=>JSON.parse(JSON.stringify(o));
const safeUrl=s=>{try{const u=new URL(s);return u.protocol==='https:'?u.href:'#';}catch{return '#';}};
function validate(s){
 if(!s||s.version!==1||!Number.isInteger(s.people)||s.people<1||s.people>30||!Number.isFinite(s.limit)||s.limit<=0||s.limit>10000000||!Number.isFinite(s.buffer)||s.buffer<0||s.buffer>100)throw Error('Invalid trip settings.');
 if(!Array.isArray(s.days)||!s.days.length||s.days.length>90||!Array.isArray(s.stays)||(s.stays.length<1||s.stays.length>30)||!Array.isArray(s.checks)||s.checks.length!==6||!s.checks.every(x=>typeof x==='boolean'))throw Error('Invalid plan structure.');
 let ids=new Set(); for(const d of s.days){if(!validDate(d.date)||typeof d.id!=='string'||ids.has(d.id)||!['city','title','subtitle','description','morning','afternoon','evening','transport','note'].every(k=>typeof d[k]==='string'&&d[k].length<=5000))throw Error('Invalid day.');ids.add(d.id);}
 for(const t of s.stays){if(!validDate(t.start)||!validDate(t.end)||nights(t)<=0||nights(t)>90||!Number.isFinite(t.rate)||t.rate<0||t.rate>10000000||!['city','name','url','note'].every(k=>typeof t[k]==='string'&&t[k].length<=5000)||safeUrl(t.url)==='#')throw Error('Invalid accommodation.');}
 if(!s.costs||Object.keys(s.costs).join('|')!==Object.keys(defaults.costs).join('|')||!Object.values(s.costs).every(n=>Number.isFinite(n)&&n>=0&&n<=10000000))throw Error('Invalid budget.');return s;
}
function migrate(s){
 if(s&&s.version===1&&s.costs&&!Object.hasOwn(s.costs,'Barcelona onward flight & extra-day costs')){
  s.costs={'Barcelona onward flight & extra-day costs':16000,...s.costs};
  if(Array.isArray(s.days)&&!s.days.some(d=>d.date==='2026-12-26'))s.days.unshift(clone(defaults.days.find(d=>d.id==='2026-12-26')));

  const nye=s.days?.find(d=>d.id==='2026-12-31');const updated=defaults.days.find(d=>d.id==='2026-12-31');
  if(nye&&nye.evening?.includes('confirmed event or public celebration')){nye.evening=updated.evening;nye.note=updated.note;nye.transport=updated.transport;}
 }
 if(s&&s.version===1&&Array.isArray(s.days)&&!s.flightDatesAdded){
 for(const id of ['2026-12-25','2027-01-09'])if(!s.days.some(d=>d.date===id))s.days.push(clone(defaults.days.find(d=>d.id===id)));
 s.flightDatesAdded=true;
 }
 if(s&&s.version===1&&!s.sameDayNaplesAdded&&Array.isArray(s.days)&&Array.isArray(s.stays)){
  for(const id of ['2026-12-26','2026-12-27']){const idx=s.days.findIndex(d=>d.id===id);const d=clone(defaults.days.find(d=>d.id===id));if(idx<0)s.days.push(d);else if(id==='2026-12-26'||s.days[idx].morning?.includes('Barcelona → Naples')||s.days[idx].morning?.includes('Arrive & settle in'))s.days[idx]=d;}
  s.stays=s.stays.filter(t=>t.name!=='Barcelona overnight · provisional');
  const naples=s.stays.find(t=>t.city==='Naples'&&t.start==='2026-12-27');if(naples)naples.start='2026-12-26';
  s.sameDayNaplesAdded=true;
 }
 return s;
}
let state=migrate(clone(defaults)),loadError='';try{const raw=localStorage.getItem(KEY);if(raw)state=validate(migrate(JSON.parse(raw)));}catch{loadError='Saved plan could not be loaded. Original plan restored; import a backup if needed.';}
let mapReady=false;
let selected=state.days[0].id,filter='All stops',editing=null,toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('saveStatus').textContent='Saved on this device · Export a copy to share with your crew';}catch{$('saveStatus').textContent='Storage unavailable — export your plan before leaving.';toast('Could not save on this device. Please export a backup.');}}
function totals(){const stay=state.stays.reduce((n,s)=>n+s.rate*nights(s),0)/state.people;const base=stay+Object.values(state.costs).reduce((a,b)=>a+b,0);return{stay,base,buffer:base*state.buffer/100,total:base*(1+state.buffer/100)};}
function updateBudgetSummary(){const t=totals();$('budgetTotal').textContent=money(t.total);$('skiAllowance').textContent=money(state.costs['Ski lessons, passes & rental']);$('costStat').textContent=money(t.total);$('groupTotal').textContent=money(t.total*state.people);$('bufferTotal').textContent=money(t.buffer);$('budgetBar').style.width=Math.min(100,t.total/state.limit*100)+'%';$('budgetBar').style.background=t.total>state.limit?'#b75b46':'#5f7d42';$('budgetRemaining').textContent=t.total<=state.limit?`${money(state.limit-t.total)} below your ${money(state.limit)} ceiling`:`${money(t.total-state.limit)} over your ${money(state.limit)} ceiling — adjust your plan`;}
function renderBudget(){updateBudgetSummary();const t=totals();$('limit').value=state.limit;$('buffer').value=state.buffer;$('budgetRows').innerHTML=`<div class="budget-row"><span>Accommodation / person</span><span>${money(t.stay)}</span></div>`+Object.entries(state.costs).map(([k,v],i)=>`<div class="budget-row"><label for="cost${i}">${esc(k)}</label><input id="cost${i}" data-cost="${esc(k)}" type="number" min="0" max="10000000" value="${v}" aria-label="${esc(k)} per person in rupees"></div>`).join('');}
function renderDay(d){const acts=[['MORNING',d.morning],['AFTERNOON',d.afternoon],['EVENING',d.evening]].map(([time,a])=>{const [title,...rest]=a.split('|');return `<div class="activity"><span>${time}</span><div><h4>${esc(title)}</h4><p>${esc(rest.join('|'))}</p></div></div>`;}).join('');return `<div class="day-cover" style="background-image:url('${photo(d.city)}')"><div class="cover-top"><span class="pill">${esc(fmt(d.date,{weekday:'short',day:'numeric',month:'short'}).toUpperCase())} · ${esc(d.city.toUpperCase())}</span><button class="edit-btn" data-edit="${esc(d.id)}">Edit day ↗</button></div><div><h3>${esc(d.title)}</h3><p>${esc(d.subtitle)}</p></div></div><div class="day-body"><p class="day-description">${esc(d.description)}</p>${acts}<div class="weather-note">↳ ${esc(d.note)}</div></div><div class="day-bottom"><span>↗ ${esc(d.transport)}</span><a target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(d.city==='Switzerland'?'Engelberg Switzerland':d.city)}">Open map ↗</a></div>`;}
function renderJourney(){const cities=['All stops',...new Set(state.days.map(d=>d.city))];if(!cities.includes(filter))filter='All stops';$('route').innerHTML=cities.map((c,i)=>`<button data-filter="${esc(c)}" class="${filter===c?'active':''}" aria-pressed="${filter===c}">${i?'0'+i+' / ':''}${esc(c)}</button>`).join('');const days=state.days.filter(d=>filter==='All stops'||d.city===filter);if(!days.some(d=>d.id===selected))selected=days[0]?.id;$('dayList').innerHTML=days.map(d=>`<button class="day-button ${d.id===selected?'active':''}" data-day="${esc(d.id)}" aria-pressed="${d.id===selected}"><span class="date">${fmt(d.date,{day:'2-digit'})}<small>${fmt(d.date,{month:'short'}).toUpperCase()}</small></span><span><strong>${esc(d.city)}</strong><span class="sub">${esc(d.subtitle.split('·')[0])}</span></span><span class="arrow">↗</span></button>`).join('');$('dayDetail').innerHTML=days.length?renderDay(days.find(d=>d.id===selected)):'<p class="empty">No days in this chapter.</p>';}
function searchStay(s,type){const city=s.city==='Switzerland'?'Engelberg, Switzerland':s.city+(s.city==='Barcelona'?', Spain':', Italy');if(type==='airbnb')return `https://www.airbnb.com/s/${encodeURIComponent(city)}/homes?checkin=${s.start}&checkout=${s.end}&adults=${state.people}&room_types%5B%5D=Entire%20home%2Fapt`;return `https://www.booking.com/searchresults.html?ss=${encodeURIComponent(s.name)}&checkin=${s.start}&checkout=${s.end}&group_adults=${state.people}&group_children=0&no_rooms=2`;}
function renderStays(){$('stayCards').innerHTML=state.stays.map((s,i)=>`<article class="stay-card"><div class="stay-art" style="background-image:url('${photo(s.city,600)}')"><span class="pill">${esc(s.city==='Switzerland'?'ENGELBERG':s.city.toUpperCase())}</span></div><div class="stay-content"><div class="eyebrow">${esc(fmt(s.start))} → ${esc(fmt(s.end))} · ${nights(s)} NIGHTS</div><h3>${esc(s.name)}</h3><p>${esc(s.note)}</p><div class="stay-rate"><b>${money(s.rate)}</b><small>target / night · whole crew · not a quote</small></div><a href="${esc(safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">View property / search ↗</a><a href="${esc(searchStay(s,'booking'))}" target="_blank" rel="noopener noreferrer">Check dates · ${state.people} adults ↗</a><a href="${esc(searchStay(s,'airbnb'))}" target="_blank" rel="noopener noreferrer">Compare Airbnb apartments ↗</a><button class="text-btn" data-stay="${i}">Edit stay & allowance</button></div></article>`).join('');const count=state.stays.reduce((n,s)=>n+nights(s),0);document.querySelector('#stays .section-head .pill').textContent=`${state.stays.length} BASES · ${count} NIGHTS`;}
function render(){state.days.sort((a,b)=>a.date.localeCompare(b.date));$('crewStat').textContent=String(state.people).padStart(2,'0')+' friends';const first=state.days[0].date,last=state.days.at(-1).date;const span=Math.round((Date.parse(last)-Date.parse(first))/86400000)+1;$('durationStat').textContent=`${span} days / ${state.stays.reduce((n,s)=>n+nights(s),0)} nights`;$('heroDates').textContent=`${fmt(first,{day:'numeric',month:'short',year:'numeric'}).toUpperCase()} — ${fmt(last,{day:'numeric',month:'short',year:'numeric'}).toUpperCase()}`;$('journeyTitle').textContent=state.days.length===13?'Thirteen days. Zero ordinary.':state.days.length+' days. Zero ordinary.';const gaps=[];for(let t=Date.parse(first);t<Date.parse(last);t+=86400000){const date=new Date(t).toISOString().slice(0,10);const cover=state.stays.filter(s=>s.start<=date&&s.end>date).length;if(cover!==1&&!['2026-12-25','2027-01-08'].includes(date))gaps.push(date);}const missingDays=span!==state.days.length;$('planWarning').hidden=!gaps.length&&!missingDays;$('planWarning').textContent='Review your edited plan: '+[gaps.length?'some overnight dates have missing or overlapping accommodation':'',missingDays?'there are gaps between itinerary dates':''].filter(Boolean).join('; ')+'. Stay dates and per-person trip costs are edited separately.';renderJourney();renderStays();renderBudget();$('checklist').innerHTML=checkLabels.map((c,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}" ${state.checks[i]?'checked':''}><span>${esc(c)}</span></label>`).join('');if(mapReady)renderMap();$('sourceLinks').innerHTML=sources.map(([title,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${esc(title)} ↗</a>`).join('');}
function field(name,label,value,type='text',full=false){return `<label class="${full?'full':''}">${label}${type==='textarea'?`<textarea name="${name}" maxlength="5000" required>${esc(value)}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" max="10000000"':''} ${type==='date'?'min="2026-01-01" max="2035-12-31"':''} required maxlength="5000">`}</label>`;}
function openEditor(kind,index){editing={kind,index};$('deleteDay').hidden=kind!=='day'||state.days.length===1;let html='';if(kind==='settings'){$('editorTitle').textContent='Make it your trip';html=field('people','Friends (1–30)',state.people,'number')+field('limit','Budget per person · INR',state.limit,'number')+field('start','Shift entire trip to start on',state.days[0].date,'date',true)+'<p class="tiny full">Shifting the start date moves every day and stay by the same number of days. Holiday-specific activities and references need manual review after a shift.</p>';}
else if(kind==='stay'){const s=state.stays[index];$('editorTitle').textContent='Your base camp';html=field('city','Destination / Airbnb search',s.city,'text',true)+field('name','Property name',s.name,'text',true)+field('start','Check-in',s.start,'date')+field('end','Check-out',s.end,'date')+field('rate','Whole crew / night · INR',s.rate,'number')+field('url','Property link · HTTPS',s.url,'url')+field('note','Notes / room configuration',s.note,'textarea',true);}
else{const d=kind==='new'?day(new Date(Date.parse(state.days.at(-1).date)+86400000).toISOString().slice(0,10),'Switzerland','Your next chapter','Make it yours','Add your plan.','Morning plan|Add details.','Afternoon plan|Add details.','Evening plan|Add details.','Add transport','Add weather or booking notes.'):state.days.find(d=>d.id===index);$('editorTitle').textContent=kind==='new'?'Add a chapter':'Rewrite the day';html=field('date','Date',d.date,'date')+field('city','Destination / filter',d.city)+field('title','Headline',d.title,'text',true)+field('subtitle','Subtitle',d.subtitle,'text',true)+field('description','Day overview',d.description,'textarea',true)+['morning','afternoon','evening'].map(k=>field(k,k[0].toUpperCase()+k.slice(1)+' · title | details',d[k],'textarea',true)).join('')+field('transport','Transport',d.transport,'text',true)+field('note','Winter / booking note',d.note,'textarea',true);}
$('editorFields').innerHTML=html;$('editor').showModal();}
$('editForm').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const candidate=clone(state);try{if(editing.kind==='settings'){candidate.people=Number(data.people);candidate.limit=Number(data.limit);if(!validDate(data.start))throw Error('Choose a valid start date.');const shift=Date.parse(data.start)-Date.parse(candidate.days[0].date);const move=d=>new Date(Date.parse(d)+shift).toISOString().slice(0,10);candidate.days.forEach(d=>d.date=move(d.date));candidate.stays.forEach(s=>{s.start=move(s.start);s.end=move(s.end);});}else if(editing.kind==='stay'){Object.assign(candidate.stays[editing.index],data,{rate:Number(data.rate)});}else{if(candidate.days.some(d=>d.date===data.date&&d.id!==editing.index))throw Error('A day already exists on that date. Edit it or choose another date.');if(editing.kind==='new'){const id=crypto.randomUUID();candidate.days.push({...data,id});selected=id;filter='All stops';}else Object.assign(candidate.days.find(d=>d.id===editing.index),data);}
validate(candidate);state=candidate;save();render();$('editor').close();toast('Plan updated. Make it a good one.');}catch(error){toast(error.message);}});
$('closeEditor').onclick=()=>$('editor').close();$('settingsBtn').onclick=()=>openEditor('settings');$('addDay').onclick=()=>openEditor('new');
$('deleteDay').onclick=()=>{if(confirm('Delete this day from your saved plan? Accommodation dates and costs remain editable separately.')){state.days=state.days.filter(d=>d.id!==editing.index);save();render();$('editor').close();}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.day){selected=b.dataset.day;renderJourney();}if(b.dataset.filter){filter=b.dataset.filter;renderJourney();}if(b.dataset.edit)openEditor('day',b.dataset.edit);if(b.dataset.stay!==undefined)openEditor('stay',Number(b.dataset.stay));});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.check!==undefined){state.checks[Number(el.dataset.check)]=el.checked;save();}if(el.dataset.cost!==undefined){if(!el.checkValidity()||el.value===''){toast('Enter a non-negative cost.');renderBudget();return;}state.costs[el.dataset.cost]=Number(el.value);save();renderBudget();}if(el.id==='limit'||el.id==='buffer'){if(!el.checkValidity()||el.value===''){toast('Enter a valid budget value.');renderBudget();return;}state[el.id]=Number(el.value);save();renderBudget();}});
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportBtn').onclick=()=>{download('winter-edit-plan.json',JSON.stringify(state,null,2),'application/json');toast('Plan exported. Your friends can import this file.');};
$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw Error('Plan file is too large.');const imported=validate(migrate(JSON.parse(await f.text())));if(confirm('Replace your saved plan with this imported plan?')){state=imported;filter='All stops';selected=state.days[0].id;save();render();toast('Crew plan imported.');}}catch(error){toast('Import failed: '+error.message);}e.target.value='';};
$('resetBtn').onclick=()=>{if(confirm('Reset all local edits and costs to the original plan? Export a backup first if needed.')){state=migrate(clone(defaults));selected=state.days[0].id;filter='All stops';save();render();toast('Original trip restored.');}};
const preparePrint=()=>{$('dayDetail').innerHTML=state.days.map(d=>`<section class="day-detail">${renderDay(d)}</section>`).join('');};
window.addEventListener('beforeprint',preparePrint);window.addEventListener('afterprint',renderJourney);$('printBtn').onclick=()=>window.print();
render();if(loadError)toast(loadError);

// Geographic overview; arrows are schematic connections, not road/rail geometry.
const mapStops={Barcelona:[2.1734,41.3851],Naples:[14.2681,40.8518],Amalfi:[14.6027,40.634],Pompeii:[14.487,40.7497],Rome:[12.4964,41.9028],Milan:[9.19,45.4642],Venice:[12.3155,45.4408],Lucerne:[8.3093,47.0502],Engelberg:[8.4049,46.8198],Zurich:[8.5417,47.3769]};
const mapLegData=[
 {id:'hyd',title:'HYD → Barcelona · overnight',date:'25 Dec',day:'2026-12-25',city:'Travel',mode:'Depart HYD 21:00 local · route pending',places:['Barcelona'],url:'https://www.google.com/travel/flights',note:'Depart Hyderabad on 25 December at 21:00 local time. Arrive Barcelona on 26 December at 08:00 local. Airline and connection details are pending. Hyderabad is outside this European map.'},
 {id:'arrival',title:'Barcelona · arrive 08:00',date:'26 Dec',day:'2026-12-26',city:'Barcelona',mode:'Schengen entry · continue to Naples',places:['Barcelona'],url:'https://www.aena.es/en/josep-tarradellas-barcelona-el-prat/airport-services/connecting-flights.html',note:'26 December, 08:00 local arrival. Entry passport control in Barcelona if this is your first Schengen arrival from outside Schengen. Continue to Naples on the same day; no Barcelona overnight. Check baggage and terminal requirements with your airline.'},
 {id:'flight',title:'Barcelona → Naples',date:'26 Dec',day:'2026-12-26',city:'Naples',mode:'Same-day onward flight',places:['Barcelona','Naples'],flight:true,url:'https://www.google.com/travel/flights',note:'Fly onward to Naples on 26 December after the 08:00 Barcelona arrival. Sleep in Naples. Flight details can be added later. Budget includes an editable INR 16,000 per-person allowance for this flight, baggage, airport transfers and arrival-day spending.'},
 {id:'coast',title:'Naples ⇄ Amalfi',date:'28 Dec',day:'2026-12-28',city:'Naples',mode:'Train + bus / quoted driver',places:['Naples','Amalfi'],back:true,note:'A return outing from Naples via Salerno. The line is schematic; use the overland transport plan and confirm winter schedules.'},
 {id:'pompeii',title:'Naples ⇄ Pompeii',date:'29 Dec',day:'2026-12-29',city:'Naples',mode:'Local train · return outing',places:['Naples','Pompeii'],back:true,note:'Keep the same Naples accommodation. Check the archaeological park’s winter opening hours.'},
 {id:'rome',title:'Naples → Rome',date:'30 Dec',day:'2026-12-30',city:'Rome',mode:'Fast train · about 1h10–1h20',places:['Naples','Rome'],note:'Three nights in Rome, including New Year’s Eve. Travel times are indicative; check the final timetable.'},
 {id:'nye',title:'Rome · paid New Year’s party',date:'31 Dec',day:'2026-12-31',city:'Rome',mode:'Room26 shortlist · event unconfirmed',places:['Rome'],url:'https://www.room26.it/',note:'Dinner first, then a ticketed indoor party with entry before midnight. Room26 in EUR is the preferred shortlist. Request written confirmation for five men, age 25, including dress code, entry cutoff, drinks and any table minimum. Allow INR 15,000–20,000 per person for the whole night. Aforisma + Toy Room is an alternative with unconfirmed 2026 prices; Jackie O’ advertises a EUR 300 dinner-and-party package, drinks extra.'},
 {id:'milan',title:'Rome → Milan',date:'2 Jan',day:'2027-01-02',city:'Milan',mode:'Fast train · about 3–3.5h',places:['Rome','Milan'],note:'Settle into Milan for three nights. Leave bags at your base while visiting Venice.'},
 {id:'venice',title:'Milan ⇄ Venice',date:'3 Jan',day:'2027-01-03',city:'Milan',mode:'Train · about 2.5–3h each way',places:['Milan','Venice'],back:true,note:'This is an out-and-back day, not a hotel move. Book an early outbound and a reserved return to Milan.'},
 {id:'alps',title:'Milan → Lucerne → Engelberg',date:'5 Jan',day:'2027-01-05',city:'Switzerland',mode:'Train connections · allow 5–6h',places:['Milan','Lucerne','Engelberg'],note:'Schematic route via Lucerne; actual train services may require additional changes. Stay in Engelberg three nights and ski on both full days.'},
 {id:'zurich',title:'Engelberg → Lucerne → Zurich',date:'8 Jan',day:'2027-01-08',city:'Switzerland',mode:'Train · morning departure',places:['Engelberg','Lucerne','Zurich'],note:'Leave the mountains early. Zurich city is optional; reach the airport at least three hours before the night flight. Arrive Mumbai on 9 January; exact flight times remain pending.'},
 {id:'bom',title:'Zurich → Mumbai · fly home',date:'9 Jan',day:'2027-01-09',city:'Travel',mode:'ZRH 8 Jan night → BOM 9 Jan',places:['Zurich'],url:'https://www.google.com/travel/flights',note:'Depart Zurich on the night of 8 January and arrive Mumbai on 9 January. Exact times, airline and connections are not supplied. Mumbai is outside this European map.'}
];
const xy=name=>[(mapStops[name][0]+1)*45,(49-mapStops[name][1])*60];
let activeLeg='arrival';
function mapPath(l){const p=l.places.map(xy);if(l.back){const[a,b]=p;const bend=l.id==='venice'?-37:24;return `M${a} Q${(a[0]+b[0])/2},${(a[1]+b[1])/2+bend} ${b} Q${(a[0]+b[0])/2},${(a[1]+b[1])/2-bend} ${a}`;}return 'M'+p.map(p=>p.join(',')).join(' L');}
function renderMap(){
const svg=$('travelMap');
svg.innerHTML='<title id="mapTitle">Travel route through Italy and Switzerland</title><desc id="mapDesc">North is up. Select a leg using the route buttons beside the map. Arrows show travel direction; dashed loops are return day trips.</desc><defs><marker id="arrowGreen" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#456341"/></marker><marker id="arrowGold" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="4" markerHeight="4" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#ba8957"/></marker></defs>'+mapCountries.map(c=>`<path class="map-country ${['Italy','Switzerland'].includes(c.name)?'featured':''}" d="${c.path}"/>`).join('')+'<text class="country-label" x="65" y="417">SPAIN</text><text class="country-label" x="530" y="360" transform="rotate(-43 530 360)">ITALY</text><text class="country-label" x="258" y="92">SWITZERLAND</text><text class="country-label" x="185" y="245">FRANCE</text><text class="country-label" x="557" y="88">AUSTRIA</text><text class="sea-label" x="270" y="511">Mediterranean Sea</text>'+mapLegData.map(l=>`<path class="route-line ${l.back?'return':''} ${l.flight?'flight':''} ${l.id===activeLeg?'selected':''}" data-map="${l.id}" d="${mapPath(l)}" marker-mid="url(#${l.back?'arrowGold':'arrowGreen'})" marker-end="url(#${l.back?'arrowGold':'arrowGreen'})"/><path class="route-hit" data-map="${l.id}" d="${mapPath(l)}"><title>${esc(l.title)}</title></path>`).join('')+mapLegData.map(l=>{const pts=l.places.map(xy);return pts.slice(1).map((b,i)=>{const a=pts[i],x=(a[0]+b[0])/2,y=(a[1]+b[1])/2,angle=Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI;return `<path d="M-7,-4 L3,0 L-7,4 Z" fill="${l.back?'#a87343':'#355735'}" transform="translate(${x},${y+(l.back?(l.id==='venice'?-18.5:12):0)}) rotate(${angle})"/>`+(l.back?`<path d="M-7,-4 L3,0 L-7,4 Z" fill="#a87343" transform="translate(${x},${y-(l.id==='venice'?-18.5:12)}) rotate(${angle+180})"/>`:'');}).join('');}).join('')+Object.entries(mapStops).map(([name])=>{const[x,y]=xy(name);const pos={Barcelona:[-50,23],Naples:[-77,3],Amalfi:[18,27],Pompeii:[35,-1],Rome:[14,5],Milan:[-59,20],Venice:[13,4],Lucerne:[-75,3],Engelberg:[18,17],Zurich:[13,-9]}[name];return `<circle class="map-point" cx="${x}" cy="${y}" r="${['Amalfi','Pompeii','Lucerne'].includes(name)?3:5}"/><text class="city-label ${['Amalfi','Pompeii','Lucerne','Engelberg'].includes(name)?'small':''}" x="${x+pos[0]}" y="${y+pos[1]}">${name}</text>${name==='Rome'?`<text class="city-label small" x="${x+14}" y="${y+23}">★ PAID NYE</text>`:''}`;}).join('');
$('mapLegs').innerHTML=mapLegData.map((l,i)=>{const d=state.days.find(d=>d.id===l.day);return `<button class="map-leg ${l.id===activeLeg?'active':''}" data-map="${l.id}" aria-pressed="${l.id===activeLeg}"><span class="leg-num">${i+1}</span><span><b>${esc(l.title)}</b><small>${d?esc(fmt(d.date)):l.date+' · original plan'} / ${esc(l.mode)}</small></span></button>`;}).join('');
const l=mapLegData.find(l=>l.id===activeLeg);$('mapInfo').innerHTML=`<b>${esc(l.title)}</b><p>${esc(l.note)}</p><a href="${l.url?esc(l.url):`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(l.places[0])}&destination=${encodeURIComponent(l.id==='zurich'?'Zurich Airport':l.places.at(-1))}&travelmode=transit${l.places.length>2?'&waypoints='+encodeURIComponent(l.places.slice(1,-1).join('|')):''}`}" target="_blank" rel="noopener noreferrer">${l.id==='arrival'?'Airport connection guide':l.id==='nye'?'Official Room26 venue':(l.flight||['hyd','bom'].includes(l.id))?'Flight search':'Open directions'} ↗</a><button class="text-btn" data-map-day="${l.day}">View day plan ↗</button><p class="tiny">Map follows the suggested route. If you change destinations, use the updated itinerary and confirm your new route.</p>`;
}
document.addEventListener('click',e=>{const leg=e.target.closest('[data-map]');if(leg){activeLeg=leg.dataset.map;renderMap();}const d=e.target.closest('[data-map-day]');if(d){const found=state.days.find(x=>x.id===d.dataset.mapDay);if(found){selected=found.id;filter='All stops';renderJourney();$('journey').scrollIntoView({behavior:'smooth'});}else toast('This original day has been removed. Choose a day from the itinerary.');}});
mapReady=true;
renderMap();

document.addEventListener('input',e=>{const el=e.target;const key=el.dataset.cost;const setting=el.id==='limit'||el.id==='buffer';if((key!==undefined||setting)&&el.value!==''&&el.checkValidity()){if(key!==undefined)state.costs[key]=Number(el.value);else state[el.id]=Number(el.value);save();updateBudgetSummary();}});
